# AMG Dataset Configuration
# Attributing Multi-granularity Multimodal Fake News Dataset

dataset:
  name: "AMG"
  data_root: "data"
  modality: "multimodal"  # text, image, multimodal

  # Data splits
  train_split: "train"
  val_split: "val"
  test_split: "test"

  # Data properties
  has_text: true
  has_image: true  # AMG has images in AMG_MEDIA folder
  has_ocr: false
  use_ocr: false

  # Preprocessing
  max_text_length: 512
  image_size: 224

model:
  type: "multimodal"  # text, image, multimodal
  num_classes: 2  # Binary classification (0=real, 1-5=fake)

  # Text encoder
  text_encoder: "bert-base-uncased"
  text_hidden_size: 768
  text_max_length: 512

  # Image encoder
  image_encoder: "resnet50"
  image_hidden_size: 2048
  image_pretrained: true

  # Fusion
  fusion_method: "concat"  # concat, attention, cross_attention
  fusion_hidden_sizes: [512, 256]
  dropout: 0.3
  activation: "relu"

training:
  # Optimizer
  optimizer: "adamw"
  learning_rate: 2.0e-5
  weight_decay: 0.01

  # Scheduler
  scheduler: "linear_warmup"
  warmup_ratio: 0.1

  # Training parameters
  num_epochs: 10
  batch_size: 32
  gradient_accumulation_steps: 1
  max_grad_norm: 1.0

  # Mixed precision
  mixed_precision: true

  # Loss
  loss_fn: "cross_entropy"
  label_smoothing: 0.0

  # Early stopping
  early_stopping: true
  patience: 3
  metric: "f1_macro"  # accuracy, f1_macro, f1_weighted

experiment:
  name: "amg_multimodal_detection"
  seed: 42
  device: "cuda"
  num_workers: 4

  # Paths
  output_dir: "outputs/amg"
  checkpoint_dir: "checkpoints/amg"
  log_dir: "logs/amg"

  # Logging
  log_interval: 100  # steps
  eval_interval: 500  # steps
  save_interval: 1000  # steps
  save_total_limit: 3

  # Evaluation
  eval_on_test: true
  compute_metrics_per_dataset: false