# FineFake Dataset Configuration
# Fine-grained Fake News Detection - Multimodal dataset with knowledge graph

dataset:
  name: "FineFake"
  data_root: "data"
  modality: "multimodal"

  train_split: "train"
  val_split: "val"
  test_split: "test"

  has_text: true
  has_image: true
  has_ocr: false
  use_ocr: false

  max_text_length: 512
  image_size: 224

model:
  type: "multimodal"
  num_classes: 2

  text_encoder: "roberta-base"  # RoBERTa works well for news
  text_hidden_size: 768
  text_max_length: 512

  image_encoder: "resnet50"
  image_hidden_size: 2048
  image_pretrained: true

  fusion_method: "concat"
  fusion_hidden_size: 512
  dropout: 0.3

training:
  optimizer: "adamw"
  learning_rate: 2.0e-5
  weight_decay: 0.01

  scheduler: "cosine"  # cosine annealing
  warmup_ratio: 0.1

  num_epochs: 12
  batch_size: 24
  gradient_accumulation_steps: 1
  max_grad_norm: 1.0

  mixed_precision: true

  loss_fn: "cross_entropy"
  label_smoothing: 0.1  # Label smoothing for better generalization

  early_stopping: true
  patience: 4
  metric: "f1_macro"

experiment:
  name: "finefake_multimodal_detection"
  seed: 42
  device: "cuda"
  num_workers: 4

  output_dir: "outputs/finefake"
  checkpoint_dir: "checkpoints/finefake"
  log_dir: "logs/finefake"

  log_interval: 100
  eval_interval: 500
  save_interval: 1000
  save_total_limit: 3

  eval_on_test: true
  compute_metrics_per_dataset: false