# MR2 Dataset Configuration
# Multimodal Rumor Recognition - Chinese/English dataset with OCR

dataset:
  name: "MR2"
  data_root: "data"
  modality: "multimodal"

  train_split: "train"
  val_split: "val"
  test_split: "test"

  has_text: true
  has_image: true
  has_ocr: true
  use_ocr: true  # Important: MR2 has OCR text

  max_text_length: 512  # Longer due to caption + OCR
  image_size: 224

model:
  type: "multimodal"
  num_classes: 3  # 0=non-rumor, 1=rumor, 2=unverified

  # Multilingual encoder
  text_encoder: "bert-base-multilingual-cased"  # Supports Chinese + English
  text_hidden_size: 768
  text_max_length: 512

  image_encoder: "resnet50"
  image_hidden_size: 2048
  image_pretrained: true

  fusion_method: "concat"
  fusion_hidden_size: 512
  dropout: 0.3

training:
  optimizer: "adamw"
  learning_rate: 2.0e-5
  weight_decay: 0.01

  scheduler: "linear_warmup"
  warmup_ratio: 0.1

  num_epochs: 12
  batch_size: 16
  gradient_accumulation_steps: 2
  max_grad_norm: 1.0

  mixed_precision: true

  # For 3-class classification
  loss_fn: "cross_entropy"
  label_smoothing: 0.0

  early_stopping: true
  patience: 4
  metric: "f1_macro"

experiment:
  name: "mr2_multimodal_detection"
  seed: 42
  device: "cuda"
  num_workers: 4

  output_dir: "outputs/mr2"
  checkpoint_dir: "checkpoints/mr2"
  log_dir: "logs/mr2"

  log_interval: 100
  eval_interval: 500
  save_interval: 1000
  save_total_limit: 3

  eval_on_test: true
  compute_metrics_per_dataset: false

  # MR2-specific: language filtering
  filter_language: null  # null, "zh", "en" - filter by language if needed